name: Run WhatsApp Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"  # restart every 6 hours
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Set environment variables
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: |
          echo "GROQ_API_KEY=${GROQ_API_KEY}" >> $GITHUB_ENV

      - name: Run WhatsApp Bot
        run: |
          npm install -g localtunnel
          node index.js &
          lt --port 3000 --subdomain zani-bot &
          sleep infinity
