name: Run WhatsApp Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Kill Previous Bot Process
        run: |
          echo "Checking for previous bot process..."
          pkill -f "node index.js" || echo "No previous process found, continuing..."

      - name: Start Bot
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: |
          echo "Starting Zani Bot..."
          npm install -g localtunnel
          node index.js
